// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using National_Train_Reservation.Data;

#nullable disable

namespace National_Train_Reservation.Migrations
{
    [DbContext(typeof(ApplicationDBcontext))]
    [Migration("20240429230306_train2")]
    partial class train2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("National_Train_Reservation.Models.Payment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CVV")
                        .HasColumnType("int");

                    b.Property<int>("Card_Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("Expiration_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.Property<string>("User_Phone_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("National_Train_Reservation.Models.Suggestions_Complaints", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Message_Type")
                        .HasColumnType("int");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Suggestions_Complaints");
                });

            modelBuilder.Entity("National_Train_Reservation.Models.Tickets", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pickup_Station")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Seat_Number")
                        .HasColumnType("int");

                    b.Property<double>("Ticket_Money")
                        .HasColumnType("float");

                    b.Property<DateTime>("Time_Pickup")
                        .HasColumnType("datetime2");

                    b.Property<int>("Train_Car_Number")
                        .HasColumnType("int");

                    b.Property<int>("Train_ID")
                        .HasColumnType("int");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Train_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("National_Train_Reservation.Models.Trains", b =>
                {
                    b.Property<int>("Journey_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Journey_ID"));

                    b.Property<TimeSpan>("Arrival_Time")
                        .HasColumnType("time");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date_Pickup")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Journey_Price")
                        .HasColumnType("int");

                    b.Property<string>("Launching_Station")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number_of_available_tickets")
                        .HasColumnType("int");

                    b.Property<int>("Number_of_stoppages")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time_Pickup")
                        .HasColumnType("time");

                    b.Property<int>("TrainNumber")
                        .HasColumnType("int");

                    b.HasKey("Journey_ID");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("National_Train_Reservation.Models.Users", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<long>("National_Pass_Number")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_phone_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("National_Train_Reservation.Models.Payment", b =>
                {
                    b.HasOne("National_Train_Reservation.Models.Users", "Users")
                        .WithMany("Payment")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("National_Train_Reservation.Models.Suggestions_Complaints", b =>
                {
                    b.HasOne("National_Train_Reservation.Models.Users", "Users")
                        .WithMany("Suggestions_Complaints")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("National_Train_Reservation.Models.Tickets", b =>
                {
                    b.HasOne("National_Train_Reservation.Models.Trains", "Trains")
                        .WithMany("Tickets")
                        .HasForeignKey("Train_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Train_Reservation.Models.Users", "Users")
                        .WithMany("Tickets")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trains");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("National_Train_Reservation.Models.Trains", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("National_Train_Reservation.Models.Users", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Suggestions_Complaints");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
